### PR TITLE
docs: add react-native-collapsible-tab-view link

### PR DESCRIPTION
**Pull request by PedroBern**
Add [react-native-collapsible-tab-view](https://github.com/PedroBern/react-native-collapsible-tab-view) to the Community-developed Navigators and Libraries.

This PR affects only the `version-5.x` of the docs.

It's a wrapper for the [react-native-tab-view](https://github.com/satya164/react-native-tab-view), exporting a navigator to integrate with react-navigation and render a collapsible header above the tab-view.

Below is the expo preview of the example app:

- [View it with Expo](https://expo.io/@pedrobern/react-native-collapsible-tab-view-demos).

<a href="https://expo.io/@pedrobern/react-native-collapsible-tab-view-demos"></a>

### CODE REVIEW

**Review by eriveltonelias — COMMENTED** [review]
Hey @PedroBern, thanks for your PR! 

How the integration with react-navigation will look like? 

did you remove the support with react-navigation ( https://github.com/PedroBern/react-native-collapsible-tab-view/pull/41#issuecomment-765441000) ?

**Comment by PedroBern** [comment]
Hi @eriveltonelias thanks for the response. Yes, it was removed in v3. I think it would be nicer to support it directly from react-navigation, in addition to the current material tab navigator. If it's appreciated I can try to work on a PR there.

The v2 still supports the integration, but v3 has much better performance, and of course, I'm not updating v2 anymore.

Also, I'm open for PRs, so anybody can add the support directly on my package 👍

**Comment by eriveltonelias** [comment]
> I think it would be nicer to support it directly from react-navigation, in addition to the current material tab navigator. If it's appreciated I can try to work on a PR there.
> 
gotcha, but could you open an rfc for that ( https://github.com/react-navigation/rfcs )?

I will close this PR for now, but all improvements are welcome :)

**Comment by PedroBern** [comment]
@eriveltonelias thanks for the suggestion, I saw some reasons of why not using reanimated v2 as default, on the [v6 roadmap](https://github.com/react-navigation/react-navigation/issues/8981) (on the comments). Also, it's probably not a good proposal: keeping 2 material tabs navigators.

I will try to add react-navigation support in the next few days and come back here with more info, can we do that?

**Comment by PedroBern** [comment]
@eriveltonelias can you reopen please? I've just opened a PR on my package, adding support to react-navigation.

https://github.com/PedroBern/react-native-collapsible-tab-view/pull/58

It's not released yet, I will update the readme and examples folder, and make it the default usage of the package. It's coming. 🎉

**Comment by eriveltonelias** [comment]
Hey, sure :) 

could you ping me when you release it on npm and update your docs?

**Comment by PedroBern** [comment]
Thanks @eriveltonelias :) It will take few more days.

**Comment by PedroBern** [comment]
closing for now.

**Pull request closed without merging**
