### PR TITLE
Update native stack navigator guide

### PR DESCRIPTION
**Pull request by WoLewicki**
Fixed missing NavigationNativeContainer in examples and added snacks to them

### CODE REVIEW

**Comment by satya164** [comment]
We don't have the container in individual navigator examples because user should have it at the root (it's in getting started guide)

**Comment by WoLewicki** [comment]
But if the function is called App, then we treat it as the root in examples, yes?

**Comment by satya164** [comment]
We can change it to not be called APP

**Comment by WoLewicki** [comment]
Should I change it and remove NavigationNativeContainer or leave it as it is?

**Comment by satya164** [comment]
@WoLewicki let's change it

**Comment by WoLewicki** [comment]
Ok, I will change it.

**Pull request merged**
