### PR TITLE
Update deep-linking.md

### PR DESCRIPTION
**Pull request by amiinous**
According to official docs (https://developer.android.com/training/app-links/verify-site-associations), the scheme and host should be defined in separate `data` tags. Initially I followed the current doc, but after doing some search I found out that combining the `scheme` and `host` into one `data` broke the universal links in Android.

### CODE REVIEW

**Comment by satya164** [comment]
Thank you

**Review by satya164 — APPROVED** [review]

**Review by satya164 — CHANGES_REQUESTED** [review]
I think there needs to be a different intent filter for this case, otherwise it'll need to match `mychat://www.example.com` which won't be correct

**Comment by amiinous** [comment]
@satya164 You're right...I separated the two deep-linking schemes.

**Review by satya164 — APPROVED** [review]
Thank you

**Pull request merged**
