### PR TITLE
Update switch-navigator to explain the use case

### PR DESCRIPTION
**Pull request by AuroreM**
**Motivation** : I was reading the documentation, and I could not understand the difference between `SwitchNavigator` and `StackNavigator`. I has to look for on StackOverflow and I find [this answer](https://stackoverflow.com/questions/49417757/what-is-the-difference-between-react-navigations-stacknavigator-and-switchnavig). I though it would be a could idea to have it in the documentation.

**Look**:
image

### CODE REVIEW

**Comment by AuroreM** [comment]
@brentvatne @vonovak Have you got a chance to look at it ? :)

**Comment by vonovak** [comment]
No worries, the PR is not forgotten. We will get to it :)

**Comment by brentvatne** [comment]
looks great, thanks!

**Comment by AuroreM** [comment]
Thanks @vonovak @brentvatne, glad to contribute :)

**Pull request merged**
