### PR TITLE
docs: changes in usage of header

### PR DESCRIPTION
**Pull request by anjushaKhandavalli**
Added documentation for the changes in the usage of header

# READ ME PLEASE!

### TL;DR: Make sure to add your changes to versioned docs

Thanks for opening a PR!

The docs cover several versions of `react-navigation`, and in some cases there are several files (for version 1, version 2 and etc.) that all describe a single page of the docs (eg. "Getting Started").

Please make sure that the edit you're making in `docs/file-you-edited.md` is also included in the file for the correct version, eg. `/versioned_docs/version-3.x/file-you-edited.md` for version 3. If such file doesn't exist, please create it. :+1:

### CODE REVIEW

**Comment by anjushaKhandavalli** [comment]
Updated the semantic pull request

**Comment by anjushaKhandavalli** [comment]
Using the header: null to hide the header in V5 leading to crashes. This got fixed by changing the header to a function that returns an empty component.

**Comment by eriveltonelias** [comment]
Hi @anjushaKhandavalli, thanks for your PR! 

on v5 you can use the `headerShown` prop to achieve this goal, for more info check the docs please https://reactnavigation.org/docs/stack-navigator/#headershown

**Comment by anjushaKhandavalli** [comment]
Yeah yes. But header: null is leading to crashes in V5

**Comment by satya164** [comment]
> Yeah yes. But header: null is leading to crashes in V5..which is allowed in V4

With React Navigation v4 and latest version of Stack Navigator, even if it doesn't crash, there's a deprecation warning if you use `header: null`.

> this is not mentioned anywhere in the document about header not accepting null in V5

If you're upgrading from older versions of navigators rather than their latest compatible versions in v4, you should first take a look at the v4 upgrade guide. This is already mentioned there.

https://reactnavigation.org/docs/4.x/upgrading-from-3.x#upgrading-packages

**Pull request closed without merging**
