### PR TITLE
docs: add TextInput to import

### PR DESCRIPTION
**Pull request by pamccombs**
It's obvious after reading the error message but is still very helpful for walking through error free.

# READ ME PLEASE!

### TL;DR: Make sure to add your changes to versioned docs

Thanks for opening a PR!

The docs cover several versions of `react-navigation`, and in some cases there are several files (for version 1, version 2 and etc.) that all describe a single page of the docs (eg. "Getting Started").

Please make sure that the edit you're making in `docs/file-you-edited.md` is also included in the file for the correct version, eg. `website/versioned_docs/version-3.x/file-you-edited.md` for version 3. If such file doesn't exist, please create it. :+1:

### CODE REVIEW

**Comment by pamccombs** [comment]
My apologies, this is my first try at contribution. I'm unsure where or how exactly to place the semantics.

**Comment by WoLewicki** [comment]
Thanks for your contribution! I think that adding such note in the code makes it less readable. It is better. It would be better if you deleted these notes and just added `import { TextInput } from 'react-native'` at the top of this snippet. Can you do it?

**Comment by pamccombs** [comment]
I've recreated a separate pull request with your suggestion. Thank you

--
Patrick "Reese" McCombs
Software Engineer

**Comment by pamccombs** [comment]
I've actually edited this one instead and have removed the other request.

**Comment by WoLewicki** [comment]
Nice! If only you could add an empty line after the import to follow the convention and then it is ready to be merged.

**Comment by pamccombs** [comment]
I have created a separate pull request with the correct changes.

**Pull request closed without merging**
