### PR TITLE
Fix a typo in createNavigator

### PR DESCRIPTION
**Pull request by Luukschoen**
removed X (or was it there on purpose?)

### CODE REVIEW

**Comment by vonovak** [comment]
hi, thanks for the PR! Yes, the X is there on purpose - `createXNavigator` refers to these: `createDrawerNavigator`, `createBottomTabNavigator` and etc. Would you find `create*Navigator` more understandable?

**Comment by Luukschoen** [comment]
Yes, I think that would be more understandable. I actually realized after creating the PR the X was there to refer to the type of Navigator, but I think an asterisk would me more suitable (since it actually is a wildcard in a way). The X made me read it in a way as if it was a specific Navigator. I think the asterisk would be a nice alteration!

**Comment by vonovak** [comment]
@Luukschoen could you change `createXNavigator` to `create*Navigator`? I'll merge the change then. Thanks.

**Comment by Luukschoen** [comment]
Did the update. Thank you @vonovak !

**Comment by vonovak** [comment]
thanks!

**Pull request merged**
