### PR TITLE
Update auth-flow.md

### PR DESCRIPTION
**Pull request by rwieruch**
Hello there. This year I wrote a pretty extensive tutorial for your library. Perhaps it's worth featuring it here :) People seemed to like it [on Twitter](https://twitter.com/rwieruch/status/1303364280855785472), so I would love to share it to more folks who are interested in it. Thanks for your efforts you are putting into this!

### CODE REVIEW

**Comment by eriveltonelias** [comment]
Hey @rwieruch thanks for your PR! 

it's a little bit confusing for me because mentions `react-native-navigation` which is another navigation library.

also, we have a dedicated auth flow section ( https://reactnavigation.org/docs/auth-flow/ ), will be cool if you have more ideas to help to improve it.

**Comment by rwieruch** [comment]
Hi @eriveltonelias 👋🏽 

So I must admit I just started using a navigation library with React Native and was quite confused that this one is just named React Navigation and that there is another one called React Native Navigation. As someone new to React Native, I'd expect someone searching for "react native navigation" or "react native router" and thus I named the tutorial like the former. But it features this library here ... 

_also, we have a dedicated auth flow section ( https://reactnavigation.org/docs/auth-flow/ ), will be cool if you have more ideas to help to improve it._

Yes and I went through it. It's good and should be kept this way. However, there are people who sometimes look beyond the documentation and want to run through an extensive tutorial. That's why I wrote this one :)

**Comment by satya164** [comment]
I think it'll be a bit weird to have official docs for auth and then link to a external tutorial right below it.

But I think we should add a new page listing external resources and list articles, videos etc. on that page.

**Comment by eriveltonelias** [comment]
maybe we can add a new title/section here? ( https://reactnavigation.org/docs/more-resources ) what do you think @satya164?

**Comment by satya164** [comment]
> maybe we can add a new title/section here? ( https://reactnavigation.org/docs/more-resources ) what do you think @satya164?

Sounds good

**Comment by eriveltonelias** [comment]
@rwieruch could you update your PR?

**Comment by rwieruch** [comment]
Sounds good! Thank you :) I don't want to add much hassle here. Just thought this might be useful for people! Will update the PR tomorrow 🚀

**Comment by rwieruch** [comment]
Closed in favor of https://github.com/react-navigation/react-navigation.github.io/pull/952

**Pull request closed without merging**
