### PR TITLE
fix: create LICENSE

### LINKED ISSUE #908: Create a license file
**Is your feature request related to a problem? Please describe.**
Create a license file

**Describe the solution you'd like**
Use [MIT License](https://choosealicense.com/licenses/mit/)

**Describe alternatives you've considered**
NONE

**Additional context**
NONE

### PR DESCRIPTION
**Pull request by Jadhielv**
### General
Create LICENSE

### Type

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [x] Fix #908

### CODE REVIEW

**Comment by Jadhielv** [comment]
@satya164 @brentvatne if you have time please take a look at this PR.

**Review by brentvatne — APPROVED** [review]
seems fine to me

**Comment by Jadhielv** [comment]
> 
> 
> seems fine to me

@satya164 @brentvatne  in this case, who **merge** this?

**Comment by brentvatne** [comment]
thanks @Jadhielv!

**Pull request merged**
