### PR TITLE
Don't use deprecated method `removeEventListener()`

### PR DESCRIPTION
**Pull request by retyui**
image

- Docs: https://reactnative.dev/docs/appstate#removeeventlistener

### CODE REVIEW

**Comment by retyui** [comment]
Hi @satya164 could you please review this PR?

**Comment by retyui** [comment]
cc @kacperkapusciak

**Comment by retyui** [comment]
CC @satya164

**Comment by retyui** [comment]
CCC @kacperkapusciak

**Review by satya164 — APPROVED** [review]
Thank you

**Pull request merged**
