### PR TITLE
Update used-by.md

### PR DESCRIPTION
**Pull request by BojanRatkovic**
Hey there! ActiveCollab is the project management tool operating since 2007.
ActiveCollab's mobile team strongly rely on React Navigation.
We would be very happy if you could list us on this page.

Thank you in advance! 🥇

### CODE REVIEW

**Review by kacperkapusciak — APPROVED** [review]
🙌

**Comment by kacperkapusciak** [comment]
@BojanRatkovic one thing before merging. Would you mind adding the same thing in `versioned_docs/version-5.x/used-by.md`? That way we could ensure consistency in the docs. Unless you've only ever used react-navigation v6 in the app but I doubt that 😄

**Comment by BojanRatkovic** [comment]
@kacperkapusciak Sure thing! We actually used version 4 as well. :) Do I need to @mention you there too?

**Comment by BojanRatkovic** [comment]
@kacperkapusciak I just updated version 5.x too. Thank you!

**Pull request merged**
