### PR TITLE
Update common-mistakes.md for wrapping AppContainer in View without flex

### PR DESCRIPTION
**Pull request by napalm272**
See github issue: https://github.com/react-navigation/react-navigation/issues/5651

# READ ME PLEASE!

### TL;DR: Make sure to add your changes to versioned docs

Thanks for opening a PR!

The docs cover several versions of `react-navigation`, and in some cases there are several files (for version 1, version 2 and etc.) that all describe single page of the docs (eg. "Getting Started").

Please make sure that the edit you're making in `docs/file-you-edited.md` is also included in the file for the correct version, eg. `website/versioned_docs/version-3.x/file-you-edited.md` for version 3. If such file doesn't exist, please create it. :+1:

### CODE REVIEW

**Comment by brentvatne** [comment]
thanks!

**Comment by napalm272** [comment]
@brentvatne thanks for the prompt responses! Do i need to modify the versioned docs or no?

**Comment by brentvatne** [comment]
yeah my bad, this one: https://github.com/react-navigation/react-navigation.github.io/blob/source/website/versioned_docs/version-3.x/common-mistakes.md

**Comment by napalm272** [comment]
Added a new pr

**Pull request merged**
