### PR TITLE
Enhance the doc about tabBarComponent

### PR DESCRIPTION
**Pull request by Albert-Gao**
Related to the discussion here: https://github.com/react-navigation/react-navigation/issues/4297

### CODE REVIEW

**Comment by brentvatne** [comment]
I'd rather see a heading in this doc that explains the use case and the solution, I think having this comment inline doesn't provide enough context

**Comment by Albert-Gao** [comment]
Yes, that would be clearer, do you mean, add a heading in the top area? Just for this issue? Or add an example for the `tabBarComponent`?

**Comment by brentvatne** [comment]
another heading in this same docs page would be good

**Comment by Albert-Gao** [comment]
Add an example below :)

**Pull request merged**
