### PR TITLE
Update screen-options-resolution.md

### PR DESCRIPTION
**Pull request by anhtuank7c**
Add example code for  **stack contains a tab navigator which contains another stack**

### CODE REVIEW

**Comment by satya164** [comment]
Thanks for the PR, but we need more details in the guide, similar to https://reactnavigation.org/docs/en/navigation-options-resolution.html

**Comment by anhtuank7c** [comment]
@satya164 I got it. I will do it when I have free time.

**Comment by WoLewicki** [comment]
This is already done in "Setting parent screen options based on child navigator's state", am I right @anhtuank7c ? If so, I would close the PR.

**Comment by anhtuank7c** [comment]
@WoLewicki true. We can close this PR

**Pull request closed without merging**
