### PR TITLE
add new backBehavior doc

### PR DESCRIPTION
**Pull request by slorber**
Hi,

Adding new switch router backBehavior to doc

Note really sure to understand how the docs versionning works. If there are versionned docs, what's the effect of modifying the undervsionned doc?

Do not merge yet, there are multiple places this must be documented. Just want to ask about the versionning system before completing the PR

### CODE REVIEW

**Comment by vonovak** [comment]
hi @slorber regarding the versioning - does the PR template help? (https://github.com/react-navigation/react-navigation.github.io/blob/source/.github/PULL_REQUEST_TEMPLATE.md) or do you find it's lacking some information?

**Comment by slorber** [comment]
@vonovak actually it was just warning me that I was probably doing something wrong, but it didn't really help me understand what to do exactly to do the right things. :)

What I understand is that maybe you expect users to modify v3 only? or default only? or both? or maybe v2/v3/default if the change does apply to v2 too? Not sure to understand how the merging happens afterward. If I need to modify v3, why should I need to modify default file too? Is default file for next version v4?

There's something unclear to me in this process, but one thing I know is that contributing doc should be easy and straightforward for anyone, and it would be helpful to avoid having to fork/clone/sync with upstream/PR to just being able to contribute a doc fix properly, and keep a workflow based on simple online markdown editing.

**Comment by slorber** [comment]
Hi @vonovak 

In the case of current new feature, should I modify:
- docs/material-top-tab-navigator.md
- website/versioned_docs/version-3.x/material-top-tab-navigator.md

Should I modify both? Should I modify the first? The second? (+ all other related tab nav files)

is `docs/material-top-tab-navigator.md` the draft for v4?

**Comment by brentvatne** [comment]
@slorber - yup, exactly

**Comment by slorber** [comment]
Thanks, just opened a correct PR here: https://github.com/react-navigation/react-navigation.github.io/pull/376

**Pull request closed without merging**
