### PR TITLE
fix: Update getting-started.md for drawer swipe gesture to work on Android

### PR DESCRIPTION
**Pull request by akmal578**
# Read Me Please

To fix drawer navigation not responding to the swipe on android, MainActivity.java need to be updated to make the gesture handlers work properly. Thus, I recommended putting the instructions in the docs for easier initial setup and saving much more time.

### CODE REVIEW

**Comment by jakub-gonet** [comment]
AFAIK android changes aren't necessary when you use hoc. Do you happen to use gesture handler 1.10.0?

**Comment by akmal578** [comment]
> AFAIK android changes aren't necessary when you use hoc. Do you happen to use gesture handler 1.10.0?

Yes I'm currently using gesture handlers 1.10.0 . Well if you think its ok then maybe we can close it

**Comment by jakub-gonet** [comment]
Try upgrading to 1.10.1 and check if there's still a problem without using native setup.

We had misnamed file responsible for hoc in rngh, and metro was prioritizing non-Android specific one (it would choose x.ts over x.android.tsx due to the metro matching ts files first and not finding '.android' alternative). It was resolved in the 1.10.1.

**Comment by akmal578** [comment]
> Try upgrading to 1.10.1 and check if there's still a problem without using native setup.
> 
> We had misnamed file responsible for hoc in rngh, and metro was prioritizing non-Android specific one (it would choose x.ts over x.android.tsx due to the metro matching ts files first and not finding '.android' alternative). It was resolved in the 1.10.1.

Already tried upgrading it and it seems working fine even without the native setup.  Thanks

**Pull request closed without merging**
