### PR TITLE
document resetOnBlur option for Bottom Tab Navigator

### PR DESCRIPTION
**Pull request by jacek213**
As discussed here: https://github.com/react-navigation/react-navigation/issues/4696#issuecomment-470307427

### CODE REVIEW

**Comment by brentvatne** [comment]
hey @jacek213! see the PR template:

> READ ME PLEASE!
> TL;DR: Make sure to add your changes to versioned docs
> Thanks for opening a PR!
>
> The docs cover several versions of react-navigation, and in some cases there are several files (for > version 1, version 2 and etc.) that all describe single page of the docs (eg. "Getting Started").
>
> Please make sure that the edit you're making in docs/file-you-edited.md is also included in the file for the correct version, eg. website/versioned_docs/version-3.x/file-you-edited.md for version 3. If such file doesn't exist, please create it. 👍

so, this PR changes `website/versioned_docs/version-3.x/file-you-edited.md` but not `docs/file-you-edited.md`, so you'll need to change `docs/file-you-edited.md` as well

**Comment by jacek213** [comment]
@brentvatne sorry about that - I'm going to fix it tomorrow morning

**Comment by brentvatne** [comment]
thanks @jacek213 !

**Comment by jacek213** [comment]
@brentvatne done!

**Comment by brentvatne** [comment]
thanks!

**Pull request merged**
