### PR TITLE
Add description about 'collapsible header' on sidebar.

### PR DESCRIPTION
**Pull request by benevbright**

### CODE REVIEW

**Comment by benevbright** [comment]
Thanks for your review!

**Comment by benevbright** [comment]
I fixed it and pushed it again :)

**Comment by vonovak** [comment]
thanks @benevbright! We'll probably make small changes to the community navigators section, so don't be surprised if the published docs look a little different.

**Comment by benevbright** [comment]
Absolutely! Thanks :)

**Pull request merged**
