### PR TITLE
Added installation of `react-native-screens`

### PR DESCRIPTION
**Pull request by burhanyilmaz**
if not added this two lines code, the app crashed on android.
Related to this issue https://github.com/react-navigation/react-navigation/issues/6267.

### CODE REVIEW

**Comment by brentvatne** [comment]
it seems that this has become required as of react-native-screens@2.0.0-alpha :O can you add these instructions to https://reactnavigation.org/docs/en/getting-started.html#install-into-an-existing-project instead?

**Comment by burhanyilmaz** [comment]
@brentvatne I added to getting started.

**Comment by ahartzog** [comment]
@burhanyilmaz the flow of the getting started is still very unclear on whether these steps are required for 0.60+

Could I recommend adding a line...here (see image) that just says "FOR ALL VERSIONS"? Right now it appears it could be a subset of the 0.59 and lower instructions. 
image

**Comment by burhanyilmaz** [comment]
@ahartzog According to SDK versions should work without problems. But it should be tested in rn versions.
You can check
**androidx.appcompat:appcompat:1.1.0-rc01**
https://androidx.tech/artifacts/appcompat/appcompat/1.1.0-rc01/
**androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02**
https://androidx.tech/artifacts/swiperefreshlayout/swiperefreshlayout/1.1.0-alpha02/

**Pull request merged**
