### PR TITLE
Update Screen change analytics tracking for expo

### PR DESCRIPTION
**Pull request by ltsharma**
The proposed google GoogleAnalyticsTracker will not work for expo based application, where developer needs to edit native modules. With this way developer can use 'expo-analytics' package to track screen.

### CODE REVIEW

**Comment by vonovak** [comment]
hi! Thanks for the PR. I believe that it would be equally beneficial to just mention the options people can use with expo - that would be https://github.com/react-native-community/react-native-google-analytics and https://github.com/ryanvanderpol/expo-analytics#readme (possibly more) and just link to their readme for users to see how to actually use the libraries.

The important part of how to detect a screen transition is already covered [here](https://reactnavigation.org/docs/en/screen-tracking.html#listening-to-state-changes) and then users can use the readme of the linked libraries to see how to actually implement the tracking. 

Linking to the library readmes instead of giving explicit code examples means less maintenance burden for us, since the library apis may change in the future and also less confusion for users when that happens. It also scales better in case more analytics solutions are available. What do you think about this? Thanks!

**Comment by ltsharma** [comment]
ok, that make sense. i will update it

**Comment by vonovak** [comment]
Thanks again for the PR @ltsharma, we discussed this PR with @brentvatne and concluded that `react-navigation` docs are not the right place to document different analytics libraries that work (or do not work) with Expo - this is something that perhaps might be covered in Expo docs, but is out of scope for the `react-navigation` docs. With this, I'm going to close this PR. Thanks again!

**Comment by brentvatne** [comment]
we need a guide about analytics libraries on the expo docs :)

**Pull request closed without merging**
